trigger: none

pool: Default

stages:
  - stage: terraforminstall
    displayName: terraform install

    jobs:
      - job: terraform
        displayName: terraform init

        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'ado_connection'
              backendAzureRmStorageAccountName: 'sunnystorage12'
              backendAzureRmContainerName: 'consunny'
              backendAzureRmKey: 'vijay-yaml'

      - job: terrafomplan
        displayName: terrafrom fmt, validate and plan

        steps:
     

          - task: TerraformTask@5
            displayName: terraform plan
            inputs:
               provider: 'azurerm'
               command: 'plan'

      
