trigger: none

pool: Default

stages:
  - stage: terraforminstall
    displayName: terraform install

    jobs:
      - job: terraform
        displayName: terraform init

        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'ado_connection'
              backendAzureRmStorageAccountName: 'sunnystorage12'
              backendAzureRmContainerName: 'consunny'
              backendAzureRmKey: 'vijay-yaml'

        
          - task: TerraformTask@5
            displayName: terrafrom validate
            inputs:
             provider: 'azurerm'
             command: 'validate'

          - task: TerraformTask@5
            displayName: terraform plan
            inputs:
               provider: 'azurerm'
               command: 'plan'
               environmentServiceNameAzureRM: 'ado_connection'

          - task: TerraformTask@5
            displayName: terraform apply
            inputs:
                   provider: 'azurerm'
                   command: 'apply'
                   commandOptions: '-auto-approve'
                   environmentServiceNameAzureRM: 'ado_connection'

          - task: TerraformTask@5
            displayName: terrafrom show
            inputs:
                    provider: 'azurerm'
                    command: 'show'
                    outputTo: 'console'
                    outputFormat: 'default'
                    environmentServiceNameAzureRM: 'ado_connection'

      
