
trigger:
- main

pool: Default

stages:

- stage: Terraform
  displayName: Terraform Init, Fmt and Validate

  jobs:

  - job: terraforminit
    displayName: Terraform Init, Fmt and Validate

    steps:

    - task: PowerShell@2
      displayName: Terraform Init
      inputs:
        targetType: 'inline'
        script: |
          terraform init

    - task: PowerShell@2
      displayName: Terraform Format
      inputs:
        targetType: 'inline'
        script: |
          terraform fmt

    - task: PowerShell@2
      displayName: Terraform Validate
      inputs:
        targetType: 'inline'
        script: |
          terraform validate

