# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

jobs:

 - job: terraforminit
   displayName: Terraform Init ,Plan

   steps:
   - task: PowerShell@2
     inputs:
       targetType: 'inline'
       script: 'terraform init'
       
   - task: PowerShell@2
     inputs:
           targetType: 'inline'
           script: 'terraform fmt'

   - task: PowerShell@2
     inputs:
        targetType: 'inline'
        script: 'terraform validate'